version: '3.3'
services:
  data-science-editor:
    image: sc-registry.fredhutch.org/data-science-editor:latest
    networks:
      - proxy
    deploy:
      restart_policy:
        condition: on-failure
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.data-science-editor.rule=Host(`data-science-editor.fredhutch.org`)"
        - "traefik.http.routers.data-science-editor-secured.rule=Host(`data-science-editor.fredhutch.org`)"
        - "traefik.http.routers.data-science-editor.entrypoints=web,web-secured"
        - "traefik.http.services.data-science-editor.loadbalancer.server.port=80" # it seems you always need to give traefik a port so it 'notices' the service
        - "traefik.http.routers.data-science-editor.tls=true"

networks:
  proxy:
    external: true